[project]
name = "otstack"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.13"
dependencies = [
    "dotenv>=0.9.9",
    "gitpython>=3.1.46",
    "pygithub>=2.8.1",
]
